export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const UPDATE_ACCOUNT_DATA_SUCCESS = 'UPDATE_ACCOUNT_DATA_SUCCESS';
export const UPDATE_ACCOUNT_DATA_FAIL = 'UPDATE_ACCOUNT_DATA_FAIL'
